### Release Pipeline for a .NET app. Not related to the repo. For training purposes only.

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  IISWebsiteName: 'Mercedes-Benz'

#resources:
#  pipelines:
#    - pipeline: 'Tedkata.TerraformDevEnv'
#       project: 'Mercedes-Benz'
#       source: 'Tedkata/TerraformDevEnv/azure-pipelines.yml'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'
    pool: 
      vmImage: windows-latest
    
    jobs:
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'Windows 11 server'
      strategy:
        runOnce:
            deploy:
              steps:
                  - checkout: none

                  - download: 'Tedkata.TerraformDevEnv'
                    name: 'DownloadBuildArtifacts'
                    displayName: 'Download Build Artifacts'
                    artifact: 'Mercedes-Benz'

                  - task: IISWebAppManagementOnMachineGroup@0
                    name: 'StopIIS'
                    displayName: 'Stops IIS Website'
                    inputs:
                      IISDeploymentType: 'IISWebsite'
                      ActionIISWebsite: 'StopWebsite'
                      StartStopWebsiteName: '${{variables.IISWebSiteName}}'
                    
                  - task: IISWebAppDeploymentOnMachineGroup@0
                    name: 'DeployIIS'
                    displayName: 'Deploy IIS Website'
                    inputs:
                      WebSiteName: '${{variables.IISWebSiteName}}'
                      Package: 'Tedkata/TerraformDevEnv/azure-pipelines.yml'
                      TakeAppOfflineFlag: true
                    
                  - task: IISWebAppManagementOnMachineGroup@0
                    name: 'StartIIS'
                    displayName: 'Start IIS Website'
                    inputs:
                      IISDeploymentType: 'IISWebsite'
                      ActionIISWebsite: 'StartWebsite'
                      StartStopWebsiteName: '${{variables.IISWebSiteName}}'              